### ISSUE TITLE
Treure punts blancs dels sprites

### ISSUE THREAD

**Issue by jaumemoral** [inlab-fib/fibemon#6]
Els sprites no eren transparents i al canviar el blanc per color transparent han quedat punts que queden molt malament sobre un fons que no sigui blanc. S'hauria de fer una mica de repassada per treure els punt blancs no transparents o bé fer servir una foto mes clara de fons per que no es notin tant.

**Comment by casassg** [comment]
Solucionat, hem canviat l'sprite.
